### ISSUE TITLE
WASM modules which export more than 1 symbol provide invalid code

### ISSUE THREAD

**Issue by Silic0nS0ldier** [JasonBock/WebAssembly.Generators#10]
Import dictionary entries aren't separated with commas, resulting in invalid syntax.

https://github.com/JasonBock/WebAssembly.Generators/blob/2aa4cd990bb59c36ed4722a6b30208bddf8cc1d5/src/WebAssembly.Generators/WasmExportBuilder.cs#L103

e.g. (source from https://github.com/GoogleChromeLabs/squoosh/tree/5595525c8a7d0020f55fac069b3de851b06a3168/codecs/jxl/dec)

```xml
<AdditionalFiles Include="jxl_dec.wasm" ClassName="Decode" Namespace="JpegXl" />
<AdditionalFiles Include="jxl_node_dec.wasm" ClassName="NodeDecode" Namespace="JpegXl" />
```

![image](https://user-images.githubusercontent.com/17376090/121871898-fdd68a80-cd47-11eb-8a1c-09acb0dbd205.png)

**Comment by JasonBock** [comment]
Whoops :(. That's definitely a problem, but hopefully it should be easy to fix. No guarantees on a timeline, but I will get to it when I can.
